package com.n7ws.back.mapper;

import java.util.List;

import com.n7ws.back.domain.ScriptDomain;
import com.n7ws.back.entity.ScriptEntity;
import com.n7ws.back.model.ScriptModel;

public interface ScriptMapper extends Mapper {
    static ScriptDomain toDomain(ScriptEntity scriptEntity) {
        return new ScriptDomain(
            scriptEntity.getUid(),
            scriptEntity.getName(),
            scriptEntity.getPath()
        );
    }

    static ScriptModel toModel(ScriptDomain scriptDomain) {
        return new ScriptModel(
            scriptDomain.uid(),
            scriptDomain.name(),
            scriptDomain.path()
        );
    }

    static ScriptEntity toEntity(ScriptModel scriptModel) {
        return new ScriptEntity(
            null, // UID will be generated by the database
            scriptModel.name(),
            scriptModel.path(),
            List.of() // Default to an empty list if services are null
        );
    }
}
